### ISSUE TITLE
Freemind 导出错误

### ISSUE THREAD

**Issue by crimx** [topcss/DesktopNaotu#10]
https://github.com/topcss/DesktopNaotu/blob/a9e585b792022180e43e8670ee8d54f78aa5e496/src/js/protocol/freemind.js#L89-L92

Freemind 的 mm 文件应该是 xml 格式，而不是 JSON

**Comment by topcss** [comment]
谢谢你的反馈。你可以直接修改这个方法，然后推送过来合并。
