### ISSUE TITLE
协议修改为GPL似乎更合适

### ISSUE THREAD

**Issue by ACTom** [topcss/DesktopNaotu#3]
很感谢作者愿意以MIT协议发布代码，不过，我刚注意到kityminder-editor是以GPLv2协议发布的(https://github.com/fex-team/kityminder-editor/blob/master/LICENSE)，所以作为直接引用了这个库的程序使用GPL似乎更合适。

**Comment by topcss** [comment]
感谢你提出的建议，GPL协议确实更适合些。
