### ISSUE TITLE
希望能添加云同步.可以同步到百度云盘或者都可以.

### ISSUE THREAD

**Issue by Dev-Wiki** [topcss/DesktopNaotu#4]

**Comment by topcss** [comment]
不打算提供基于云同步的功能。有几个原因：
1、云盘可能会挂（各类网盘挂得差不多了，百度目前坚挺）
2、在线版的脑图目前可用，你可以继续使用。但是你可能也看到了最近百度DOC也挂了，在线脑图能挺多久还未知。
3、推荐使用自己的同步方案，不依赖三方商业产品。

推荐我自己的用法：
1、用本地搭配GIT进行版本管理
2、自己搭建一个在线的、私有的GIT服务器，用来实现同步

**Comment by Dev-Wiki** [comment]
@topcss 我目前是使用的Simple Mind + 坚果云/Google 云端硬盘的方案

**Comment by Dev-Wiki** [comment]
百度脑涂官网经常抽风,我先已经不敢用了.准备放弃.经常503...

**Comment by topcss** [comment]
是的，官网是经常抽风，据说团队解散了，只有一个人在运维。我将上面的文件全部下载到本地，提交到自己搭建的GIT服务器，这样单位，家里都可以用，还有历史版本信息。我觉得还挺好的。
