### ISSUE TITLE
图片问题还需解决

### ISSUE THREAD

**Issue by farkaway** [topcss/DesktopNaotu#5]
图片搜索，和上传图片功能室废的，而使用图片外链的话，这就不是离线版本的了。

格式问题，如果能支持XMIND 等格式的导入导出，无疑是更好的。KM用起来很方便，唯一麻烦的是，我信不过百度，一旦百度下线KM ，就无法再导出为XM了。

**Comment by topcss** [comment]
离线版的图片建议用外部链接，这是基因决定的。在线版百度脑图，在你上传图片后，它会生成一个链接，最终你看到的图片实际上也是一个外部链接的图片。

此外，从技术角度说：
脑图文件是一个简单的JSON格式的文件，不方便存储图片。如果非要存图片，就需要存类似base64的字符了，它需要修改底层的渲染方式。

**Comment by Dev-Wiki** [comment]
simple mind 这种还不错,还可以添加选择框,已经做了的可以勾选.
![image](https://user-images.githubusercontent.com/12946956/30102850-723c47ec-9323-11e7-949b-8741120d1f80.png)

**Comment by farkaway** [comment]
关于图片的储存，我认为类似于MD，存在相对路径下，是唯一的办法了，参考Typora ，把图片放到 文件相同层级，然后拖进来，自动转换为 相对路径。当然更方便的做法我觉得是，图片直接拽进来，然后就自动复制文件到某位置，当然些的做法就是每一个KM项目都是由文件夹构成，对于文件管理而言麻烦就大了。

**Comment by topcss** [comment]
目前市场上很多软件，如果内容需要包含“文件”或者“图片”，一般采用压缩文件存储，然后改个自己的后缀名。你说的这种MD的存法，其实也是可以的，但它每次移动都需要把图片文件夹移动走，还是比较麻烦，也可能造成图片文件找不到路径的问题。MD文件在目录中相对比较固定。
最后，还是推荐用外链接。

**Comment by Dev-Wiki** [comment]
是的外链比较方便,

**Comment by farkaway** [comment]
好吧，那就外链吧，就是有时候外链不太稳定。自建服务器也挺麻烦的。。
不过图片终究不是脑图的核心功能需求，无所谓了

**Comment by topcss** [comment]
请使用外部链接的图片，操作如下：
![folding](https://user-images.githubusercontent.com/2252451/31594065-5253e35c-b265-11e7-9ac4-5f681705c799.gif)

**Comment by aaja** [comment]
用到图片方恨少啊。没法联网怎么办哦。

**Comment by topcss** [comment]
嗯，是挺麻烦的，只能自建服务器了。
