### ISSUE TITLE
每次进行一个操作，就会不停的弹出保存对话框，

### ISSUE THREAD

**Issue by zxj19951029** [topcss/DesktopNaotu#6]
比如添加一个节点，或者修改一个节点，就会一直要人保存，暂时没法用啊，求大神解决

**Comment by topcss** [comment]
这个版本会自动保存，所以需要指定一个保存路径。如果不需要这个功能，可以用前一个版本。

**Comment by topcss** [comment]
将自动保存功能加入菜单中了，默认打开。如果你不需要自动保存功能，可以点击 文件
-> 自动保存 禁用该功能，就不会提示保存框了。

**Comment by topcss** [comment]
window 32位、64位 、linux 已经编译最新版，你可以下载使用，osx 版本随后会更新。
