### ISSUE TITLE
MAC版复制和粘贴快捷键无法使用

### ISSUE THREAD

**Issue by AlfredQuan** [topcss/DesktopNaotu#7]
版本为0.1.2，其他快捷键都可以正常使用，只有复制和粘贴键不能使用。windows版一切正常。

**Comment by topcss** [comment]
这是 kityminder-editor 内部的问题，短时间内未必能解决。你可以先用其他方法代替该操作。

**Comment by AlfredQuan** [comment]
好的非常感谢




Alfred




在2017年10月17日 15:50，Jack<notifications@github.com> 写道：

这是 kityminder-editor 内部的问题，短时间内未必能解决。你可以先用其他方法代替该操作。

**Comment by topcss** [comment]
你好，我在编辑菜单加入了：剪切、复制、粘贴的功能。你可以下载新版，暂时用菜单代替键盘操作。

**Comment by topcss** [comment]
OK , 0.1.4 的版本已经解决了该问题，可以下载新版放心使用了。

**Comment by AlfredQuan** [comment]
感谢感谢

**Comment by jjeejj** [comment]
@topcss  Mac 的复制和粘贴快捷键还是无法使用，我是把最新版本的代码 `clone` 下来本地跑起来的

Mac 版本 MacOS Sierra 10.12.6

**Comment by topcss** [comment]
你可以用在 Mac 下，先用菜单的复制粘贴功能试试。有时间我再看看。

**Comment by jjeejj** [comment]
@topcss  都试过呢，菜单的复制粘贴功能也不行。我看网上的解决方案，是加菜单，我看代码菜单也加了啊

**Comment by topcss** [comment]
哇哦，真棒。我试试其他平台通用不。

**Comment by topcss** [comment]
> @topcss 这个问题，Mac 的复制和粘贴快捷键 不能使用的问题。我已经解决了，使用 菜单自带的 `role` 字段就可以了 [commit](https://github.com/jjeejj/DesktopNaotu/commit/5566a4087fadb7e4a7ba3b55af9acc7ebadbe980)。 你可以试下
> 
> ![image](https://user-images.githubusercontent.com/15176971/46568667-4294ab80-c97b-11e8-8b75-e093b151be51.png)

你把代码调整一下。需要用`role`的都加上，注释取消掉，然后重新提交一次吧。
