### ISSUE TITLE
请问在ubuntu16.04下如何使用

### ISSUE THREAD

**Issue by sadscv** [topcss/DesktopNaotu#9]
下载linux版本压缩包之后，并没有看到关于如何安装使用的介绍。

**Comment by topcss** [comment]
在Ubuntu下，一般直接解压就可以使用的。如果不行，找到入口文件（带图标的那个），右键打开对话框，勾选下面这个选项，然后就再次打开试试。
![ubuntu](https://user-images.githubusercontent.com/2252451/34086053-b127e4e2-e3d3-11e7-8ebe-eb2187563e7d.png)

**Comment by sadscv** [comment]
thanks

**Comment by topcss** [comment]
解决了吗？

**Comment by yinmazhong** [comment]
`chmod +x DesktopNaotu`
`./DesktopNaotu`
